#Assignment Operators
"""
Operator Example Same As
"+=	x += 3	x = x + 3"	
"-=	x -= 3	x = x - 3"	
"*=	x *= 3	x = x * 3"	
"/=	x /= 3	x = x / 3"
"%=	x %= 3	x = x % 3"
"//=	x //= 3	x = x // 3"	
"**=	x **= 3	x = x ** 3"	
"&=	x &= 3	x = x & 3"	
"|=	x |= 3	x = x | 3"	
"^=	x ^= 3	x = x ^ 3"
">>=	x >>= 3	x = x >> 3"	
"<<=	x <<= 3	x = x << 3"
"""